### PR TITLE
Enable ksm

### PR DESCRIPTION
**Pull request by mikalstill**

### CODE REVIEW

**Review by mandoonandy — COMMENTED** [review]
Should we use the ksmtuned service? 
That would keep the config in a location that would be more easily found.
(I have no experience using it but presumably it does it's job?)

**Comment by mikalstill** [comment]
I initial tried ksmtuned and I couldn't get it to work, I don't remember why. I'd be inclined to just do it our way (which is effectively systemd's way) and not add another daemon to the boxes. Thoughts?

**Comment by mandoonandy** [comment]
If it's been tried and it failed I agree.

**Comment by mandoonandy** [comment]
I think this should be in v0.2.2. Agreed?

**Comment by mikalstill** [comment]
Agreed. I just cherry picked it while I was doing the MTU thing.

**Pull request merged**
